[package]
name = "rledger"
version = "0.1.0"
authors = ["Rik Chilvers <rikchilvers@fastmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
nom = "6.0"
time = "0.2"
