[package]
name = "reader"
version = "0.1.0"
authors = ["Rik Chilvers <rikchilvers@fastmail.com>"]
edition = "2018"

[dependencies]
journal = { path = "../journal" }
time = "0.2"
rayon = "1.5"

[dev-dependencies]
criterion = "0.3"
